### PR TITLE
Fix readme commands

### PR DESCRIPTION
**Pull request by hogoww**
I don't know whether I missed something or not, but the command I use are based on the .sh script.
The readme now reflects that.
I also suggest to remove the removing the intermediary naming issues with the extra directory to simplify the readme.

### CODE REVIEW

**Comment by ErikOnBike** [comment]
I added the extra working directory to prevent users from 'polluting' the repo and accidentally committing additional files. But that is a precaution which I should not bother with, because it will obvious when merging PR's. So thx for making it simpler this way. :-)

**Comment by hogoww** [comment]
I thought it could be nice to do something similar, but inside the repo with a build directory & a .gitignore.
A bit similar to what CMake et al do.
What do you think? 
I might make it if you're interested.

**Comment by ErikOnBike** [comment]
That was what I was thinking about as well. If you like, you're certainly free to add it. Would be really nice.

**Comment by hogoww** [comment]
> That was what I was thinking about as well. If you like, you're certainly free to add it. Would be really nice.

Just so I know, are you set in having it executed in a bash script?
Would that be a problem if it was rewritten in Pharo?

**Comment by ErikOnBike** [comment]
I like the bash script for being able to run things in an automated environment (GitLab CI or GitHub Actions). But starting a Pharo image to perform the different tasks is perfectly legit as well of course. So no problem if written in Pharo itself. Should be able to run headless (for the mentioned environments). And ideally also work sort of incrementally. So loading the different required packages should be done with a 'saveSnapshot' when finished succesfully, but running the final 'bootstrap' step should not, allowing the image to be used multiple times from exactly the same state. (Hope I'm being clear here ;-).

**Pull request merged**
